include/mimalloc-types.h, src/alloc-override-osx.c, src/alloc-override-win.c, src/page-queue.c
aligment -> alignment
purgable -> purgeable
thead -> thread
=> Fix spelling errors

readme.md
"can be buil**d** in..." now fixed to "can be buil**t** in..."
=> Fixed a small typo in the readme.

src/os.c
Add missing argument in mi_mmap()
=> Fix build on NetBSD

include/mimalloc-internal.h
Tested with Ubuntu Linux 18.04 LTS running on Marvell/Cavium ThunderX,
which consists of Armv8 based processors.
=> Support ARM/Aarch64 TLS register fastpath

azure-pipelines.yml
After merging this PR, you will need to install [the "Azure Pipelines" app from the Marketplace](https://github.com/marketplace/azure-pipelines) on your repository.
With this, you can point users to the build artifacts, as a partial fix for https://github.com/microsoft/mimalloc/issues/37.
=> Set up CI (Azure Pipelines)

readme.md
Teeny tiny change, just came across it while reading.
=> is it -> as it

include/mimalloc-atomic.h, include/mimalloc-internal.h, include/mimalloc-types.h, include/mimalloc.h
=> Remove underscore prefixes to match c lanuguage standard

include/mimalloc-types.h
Fixed a typo when reading comments.
=> Fix typo numbes -> number

include/mimalloc-internal.h
Most processors have carry flags which they set on addition overflow, so
it is a good idea to access them whenever possible. Most of them also
have widening multiply instructions that can be used to detect overflow
of the non-widening version. Both GCC and Clang offer a way to detect an
overflow for security critical applications.
Reference:
https://clang.llvm.org/docs/LanguageExtensions.html#checked-arithmetic-builtins
=> Use checked unsigned multiplication extension of GCC/Clang

src/os.c
this platform allows to tag them per application up to 255.
=> darwin, tracking anonymous page lifetime.

CMakeLists.txt
=> build fix for arm, adding native arch flag to be able to generate

src/os.c
=> Fix typo in comment

src/os.c
Patched this so I can build it in alpine docker containers.
=> Posix / Musl Compatibility

doc/mimalloc-doc.h
Issue #266 will be fixed after a new doxygen run.
=> Fix documentation

CMakeLists.txt, src/os.c
TLS unsupported thus disabled.
=> haiku support.

src/os.c
The former to notify the pages are available for other processes,
the latter is needed for proper counting in case those pages where
tagged as reusable previously otherwise is a no-op, all for better
RSS reporting for task_info apps.
=> On Darwin, using MADV_FREE_REUSABLE/MADV_FREE_REUSE.

LICENSE, doc/mimalloc-doc.h, include/mimalloc-atomic.h, include/mimalloc-internal.h, include/mimalloc-new-delete.h, include/mimalloc-override.h, include/mimalloc-types.h, include/mimalloc.h, src/alloc-aligned.c, src/alloc-override-osx.c, src/alloc-override.c, src/alloc-posix.c, src/alloc.c, src/arena.c, src/bitmap.c, src/bitmap.h, src/heap.c, src/init.c, src/options.c, src/os.c, src/page-queue.c, src/page.c, src/random.c, src/region.c, src/segment.c, src/static.c, src/stats.c, test/test-api.c, test/test-stress.c
Each source file has been changed according to relevant Git activities.
=> Bump copyright date

include/mimalloc-override.h, include/mimalloc.h, src/alloc-override.c, src/alloc-posix.c, test/main-override.c
=> introduces netbsd's reallocarr overriding.

include/mimalloc.h
=> Tweak documentation for mi_heap_area_t::used.

CMakeLists.txt, azure-pipelines.yml, src/init.c, test/test-api-fill.c, test/test-api.c, test/testhelper.h
Another PR not necessarily meant for merging, but to run CI checks.
Contains part of the changes discussed in #508.
=> MSVC late cleanup

CMakeLists.txt, azure-pipelines.yml, test/test-api-fill.c, test/test-api.c, test/testhelper.h
The test from #507, with some reorganization (split into separate tests, tweaks to CMake to reduce redundancies).
=> Add tests for zero initialization, debug fill

src/alloc-override.c, src/random.c
=> fix build on older macOs releases, aligned_alloc only from catalina.

include/mimalloc.h
As discussed in https://github.com/microsoft/mimalloc/pull/625:
- Move some repeated code to base classes.
- Protect the shared_ptr with the heap.
=> Refactor C++ allocators to be DRY and protected

src/prim/unix/prim.c
=> fix build on freebsd.

CMakeLists.txt, src/prim/unix/prim.c
Allowing to disable transparent huge pages on Linux/Android, so we avoid affecting the whole system (such as /sys/kernel/mm/transparent_hugepage/enabled).
=> new Linux/Android option proposal.

include/mimalloc/prim.h
This is a port of the PR https://github.com/python/cpython/issues/125444
=> Fix illegal instruction for older Arm architectures

readme.md
=> Fix a Typo

src/prim/unix/prim.c
Please consider adding QNX support.
=> support building for QNX
