src/stats.c
`mi_process_info()` doesn't return a size.
=> Fix mi_process_info placeholder prototype

doc/mimalloc-doc.h, include/mimalloc-atomic.h, include/mimalloc-internal.h, include/mimalloc-types.h, include/mimalloc.h, src/alloc-aligned.c, src/alloc-override-osx.c, src/alloc-override-win.c, src/alloc-override.c, src/alloc.c, src/heap.c, src/init.c, src/options.c, src/os.c, src/page-queue.c, src/page.c, src/segment.c, src/static.c, src/stats.c
To be consistent with other Microsoft open source projects, each source
file points to the file "LICENSE" in top-level directory.
=> Clarify top-level license file

src/stats.c
clock_gettime(CLOCK_REALTIME, &ts) is equivalent to timespec_get(&ts,
TIME_UTC) in C11.
It has the advantage that avoids the following building error when building
with macOS:
warning: 'timespec_get' is only available on macOS 10.15 or newer
[-Wunguarded-availability-new]
=> Use clock_gettime() instead of timespec_get()

include/mimalloc.h
=> Use `void` in the signatures of parameter-less functions

CMakeLists.txt, doc/mimalloc-doc.h, docs/build.html, docs/overrides.html, include/mimalloc-internal.h, readme.md, src/alloc-override-osx.c
In 2012, with the release of OS X 10.8 Mountain Lion, the name of the
system was shortened from Mac OS X to OS X. In 2016, with the release
of macOS 10.12 Sierra, the name was changed from OS X to macOS to
streamline it with the branding of Apple's other primary operating
systems: iOS, watchOS, and tvOS.
Reference: https://en.wikipedia.org/wiki/MacOS
=> Apple rebrands "OS X" as "macOS"

CMakeLists.txt
- Do not define MI_MALLOC_OVERRIDE when built as a static library
- Use different output names for shared lib and static lib
=> Fix CMake configuration on Windows

src/init.c
MI_DEBUG is a macro rather than a variable.
=> Correct the use of MI_DEBUG by conditional build

CMakeLists.txt, src/alloc-override.c
GCC's default visibility is "public" but can be changed to
"hidden" with the argument "-fvisibility=hidden".
Tested with x86_64 / Ubuntu Linux 18.04 LTS:
[before]
$ nm -g -C libmimalloc.so | grep "T " | wc -l
142
[after]
$ nm -g -C libmimalloc.so | grep "T " | wc -l
93
This patch does not change the build on macOS.
=> Avoid unnecessary symbol exposure with ELF-based systems

src/alloc-override.c
Red Hat Linux was discontinued by Red Hat in 2003. It would make sense
to address glibc-based Linux distributions rather than Red Hat Linux.
Reference: https://en.wikipedia.org/wiki/Red_Hat_Linux
=> Clarify the comment about Linux distributions

src/alloc-override.c
With the new release of the GCC 9 compiler the operation of -Wmissing-attributes warnings has also been extended to aliases: this causes a warnings if the alias has less attributes than its target.
This warnings does not actually indicate a problem in the mimalloc code and you could safely ignore it by adding "-Wno-missing-attributes" to the CFLAGS, however I was not going to use a "hack" to hide the warning when compiling alloc-override .c
So this patch solves the problem simply by using an attribute (present only in GCC> = 9) that copies the attributes of another function, since this attribute is exclusive only for GCC 9 (or later) I had to use a simple precompiler instruction to add the "copy" attribute only with GCC 9.
More information about the "copy" attribute is available here: …
=> Suppressed the new GCC 9 -Wmissing-attributes warnings

include/mimalloc-atomic.h, src/alloc.c, src/init.c, src/os.c, src/stats.c
This makes mimalloc compatible with the WebAssembly Standard Interface.
I'm considering it as a dlmalloc replacement for wasi-libc, and have been successfully running it in this scenario.
=> Port to WebAssembly

src/options.c
mi_option_get is called frequently in stress tests, and the patch adds
extra hint to the compiler to emit instructions that will cause branch
prediction to favour the "likely" side of a jump instruction.
=> Add branch prediction hint for mi_option_get

src/memory.c
Original code did not compile with MI_USE_CXX=ON as function
mi_is_in_heap_region was declared noexcept through macro mi_attr_noexcept
but defined without specification, i.e. implicitly with noexception(false)
Just adding the macro in the definition is enough to fix the issue
(tested with gcc 8.3.5)
=> Fix C++ signature of function mi_is_in_heap_region

src/os.c
MAP_HUGE_2MB is linux specific and the related header
is not automatically included.
=> linux build correction

CMakeLists.txt
Part of the motivation is to work around the issue I'm commenting on in https://github.com/microsoft/mimalloc/pull/140#issuecomment-525786712, but this can be more generally useful for downstream consumers.
=> Add an option to disable building tests

include/mimalloc-atomic.h
Changed `mi_atomic_yield();` to `mi_atomic_yield(void);` in order to match its function prototype.
=> Avoid the use of variable argument list function

include/mimalloc-internal.h
extend the exception used for macOS to cover also OpenBSD (tested in 6.4+)
and DragonFlyBSD (tested in 5.6.2)
=> avoid deadlock with BSD systems that call malloc from the dynamic linker

CMakeLists.txt, readme.md
WORKING_DIRECTORY indicates the path where the installation will happen. `mi_install_dir` already has prefix `CMAKE_INSTALL_PREFIX` in it; hence, `WORKING_DIRECTORY ${CMAKE_INSTALL_PREFIX}/${mi_install_dir}/..` is not correct.
=> Symbolic link creation did not work due to incorrect argument. #166

src/alloc.c, test/test-api.c
This is a subtle one. The bug only happens with MI_SECURE, you need debug assertions enabled to see it in the test suite, and it is a bit non-deterministic, so it has to run a few times. Checkout the test without the fix and you should be able to repro the assertion failing by running `cmake -DCMAKE_BUILD_TYPE=Debug -DMI_SECURE ../.. && make -j9 && ./mimalloc-test-api` a few times.
First, you need an aligned allocation. The alignment and size have to be such that "adjust" is nonzero, i.e. the returned pointer is offset from the start of a block. An example is size=4097, align=4096.
Then, you need to call mi_usable_size() on that allocation. In that function, block is cast directly from p. Casting this is invalid with aligned pointers. mi_page_usable_size_of is then called on "block", …
=> Don't call mi_page_usable_size_of with an aligned pointer

azure-pipelines.yml
Currently, all Windows builds are using `Debug|x64` configuration. For example, you can see the CTest steps with Release build cost 20+ seconds, which means it is using the debug binary.
=> Fix Windows builds on Azure Pipelines

CMakeLists.txt, src/alloc-override-osx.c, src/alloc-override.c, src/static.c
This series of patches fixes several glitches around OS X zone implementation:
* Signature of ``malloc_size`` is corrected
* Zone implementation is added into static object
* ``zone_size`` function is implemented, otherwise free does not know which zone to use in order to free the pointer (see ``find_registered_zone`` in https://opensource.apple.com/source/Libc/Libc-594.1.4/gen/malloc.c)
=> Provide several fixes around OS X zone overrides

CMakeLists.txt, include/mimalloc-types.h, src/options.c
Currently warnings / errors are enabled by default in debug build. Otherwise they could be enabled only via environmental variable or API option call. Add possibility to specify the default during the build time. This simplifies e.g. integration of the library into bigger projects as no source changes would be required.
=> Add cmake option to specify whether warnings / errors are enabled by default

CMakeLists.txt
We need to statically link mimalloc in a `PIC` shared object. `gcc` requires mimalloc to be compiled with `-fPIC`.
=> Allow static version to compile with PIC

src/alloc-override.c
Apparently gcc 6 defines __cpp_aligned_new in C++14 mode, however no std::align_val_t is available there for obvious reasons.
=> Fix override condition for sized dealloc with gcc 6

CMakeLists.txt
This would allow one to enable building of object or static library if mimalloc is integrated as a vendor component as a part of larger build system.
=> Add possibility to selectively enable / disable builing of different targets

src/page.c
Could be triggered by specifying tight ulimit and some allocation workloads (e.g. doing bunch of realloc() in one thread and freeing in another).
=> In OOM case try to force collect memory and retry the allocation

src/os.c
VS2019 code analysis gives following warning:
warning C26451: Arithmetic overflow: Using operator '+' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '+' to avoid overflow (io.2).
=> fix: avoid warning

src/init.c
Only call mi_get_default_heap once.
=> use stored pointer #257

src/static.c
In order to avoid `_DEFAULT_SOURCE` redefinition warnings, I've wrapped the define statement with an `ifndef`.
=> Adding conditional _DEFAULT_SOURCE definition

src/options.c
`crt_externs.h` is available only available with iOS-13 sdk. we
therefore add a `__has_include` check to see if it is actually available
=> iOS compile fix

src/region.c, src/segment.c
I don't have small example which reproduce access violation, but I had access violation in one project which is able to recover from std::bad_alloc with standard allocators and with tcmalloc, but was crashing with mimalloc (using vs2015 and vs2019).
Only `region.c` change was needed to fix a crash, but I've added code in other cases when `_mi_mem_commit` result was ignored just in case. I don't know enough about mimalloc, maybe some additional deinitialization is needed, but at least my crash is gone with such fix.
I've only tested this fix with mimalloc 1.6.4 and not with dev branch, but i see that other PRs created vs dev branch, so I've did the same.
=> Fix rare access violation on out of memory

src/stats.c
Haiku does not provide page faults statistics only system wide.
=> Haiku build fix.

include/mimalloc-internal.h
Now mimalloc builds on x32, one test fails though.
```
test: malloc-zero...  ok.
test: malloc-nomem1...  mimalloc: warning: mi_usable_size: pointer might not point to a valid heap region: 0x73400100
(this may still be a valid very large allocation (over 64MiB))
mimalloc: warning: (yes, the previous pointer 0x73400100 was valid after all)
mimalloc: warning: mi_usable_size: pointer might not point to a valid heap region: 0x73400100
(this may still be a valid very large allocation (over 64MiB))
mimalloc: warning: (yes, the previous pointer 0x73400100 was valid after all)
FAILED: /root/src/mimalloc/test/test-api.c:85:
{ result = (mi_malloc(SIZE_MAX/2) == NULL); }
test: malloc-null...  ok.
test: calloc-overflow...  mimalloc: error: allocation request is too large (1448817038 * 4294967 bytes) …
```
=> fix for x32 builds

include/mimalloc-internal.h, test/test-stress.c
The pthread slot approach is somewhat buggy (pretty visible
with the stress unit test which segfault more or less randomly,
but the stats never show up).
Using the default approach instead, the test passes eventough
it s relatively slow (e.g 1.5 sec on FreeBSD vs 4.5 on DragonFly with same
machine).
=> DragonFly support fix (for 5.8.x and forward).

include/mimalloc.h, src/options.c
Warnings happen normally and could be safely ignored in the most cases, however errors, if enabled, should not be ignored. Currently since warnings and errors share the same counter we effectively stop showing errors after 16 warnings (which happen all the time).
Use different counters for errors and warnings to fix this issue.
=> Do not use the same counter for warnings and errors

src/bitmap.c
number of leading zeros is unsigned.
=> mi_bitmap_try_find_claim_field_across

CMakeLists.txt
Fixes #340 
There is the alternative between not stetting anything and using `march=armv8`. From my understanding, they produce exactly the same results for now.
=> Don't set march=native on Apple Silicon

include/mimalloc-override.h
Use of `strndup` in override header has the wrong number of arguments
=> Fix strndup override

include/mimalloc-atomic.h
adding clobber for ARM and preventing older 32 bits chips not supporting this instruction.
=> Restricts cpu yield instructions a little.

include/mimalloc-internal.h
=> Use tpidrro_el0 for thread local storage in macOS-arm64

CMakeLists.txt
As _mimalloc_ relies heavily on `__cplusplus` - which is not properly set by the MSVC compiler - a compiler flag is in order.
This patch is based on the following StackOverflow answer:
https://stackoverflow.com/a/60890947/1254880
=> Add /Zc:__cplusplus to MSVC compiler flags

include/mimalloc-types.h, src/alloc.c, src/heap.c, src/init.c, src/stats.c
Unify statistic collection:
* For MI_STAT == 0 no allocation stats are collected
* For MI_STAT == 1 only aggregated values (across normal, large and huge heaps) are collected
* For MI_STAT == 1 separate per-bin collection for normal heap is done as well
=> Unify statistics collection

src/stats.c
For some reasons unknown to me the current values of stat counters are never printed.
This makes is quite hard to use printing during the debugging in the middle of the program run.
=> Print current values of stat counters as well.

include/mimalloc-internal.h, src/alloc-aligned.c, src/alloc-posix.c, src/alloc.c, src/heap.c, src/init.c, src/options.c, src/random.c
This patch is relatively small and replaces internal calls to `memcpy()` with calls to `_mi_memcpy()`. This function is defined on Windows x86(_64) platforms to be the `_mi_memcpy_rep_movsb()` implementation that is only available on those platforms, while simply using `memcpy()` on other platforms where the issue presented in #201 is not present.
=> resolve #201 with a platform-selective REP MOVSB implementation

include/mimalloc-internal.h, readme.md, src/alloc-override.c, src/options.c, src/stats.c
Quoted from "Porting UNIX/Linux Applications to OS X,"[1]
* macro `__MACH__` is defined if Mach system calls are supported;
* macro `__APPLE__` is defined in any Apple computer.
Macro `__MACH__` is not dedicated to macOS since GNU/Hurd runs on a Mach-based microkernel (gnumach) [2], `__MACH__` is defined by the compiler, leading to potential confusions.  The solution is just changing the checked identifier (i.e. `__APPLE__`), so it is really used only on macOS.
[1] https://developer.apple.com/library/archive/documentation/Porting/Conceptual/PortingUnix/compiling/compiling.html
[2] https://www.gnu.org/software/hurd/microkernel/mach/gnumach.html
=> Revise the use of macOS predefined macro

include/mimalloc-internal.h
Android's Bionic libc stores the thread ID in TLS slot 1 instead of 0 on 32-bit ARM and AArch64. Slot 0 contains a pointer to the ELF DTV (Dynamic Thread Vector) instead, which is constant for each loaded DSO.
Because mimalloc uses the thread ID to determine whether operations are thread-local or cross-thread (atomic), all threads having the same ID causes internal data structures to get corrupted quickly when multiple threads are using the allocator:
```
mimalloc: assertion failed: at "external/mimalloc/src/page.c":563, mi_page_extend_free
assertion: "page->local_free == NULL"
mimalloc: assertion failed: at "external/mimalloc/src/page.c":74, mi_page_is_valid_init
assertion: "page->used <= page->capacity"
mimalloc: assertion failed: at "external/mimalloc/src/page.c":100, …
```
=> Fix thread ID getter on Android ARM/AArch64

src/alloc-override.c
As Conda's gcc is upgraded from 7 to 9, it now defines `_GLIBCXX_HAVE_ALIGNED_ALLOC` and we cannot use this macro to detect Conda.
According to the man page (https://linux.die.net/man/3/aligned_alloc) `_ISOC11_SOURCE` is better test,
but for .c codes only `__USE_ISOC11` is defined.
compiler                   | _GLIBCXX_HAVE_ALIGNED_ALLOC | _ISOC11_SOURCE | __USE_ISOC11
---------------------------|-----------------------------|----------------|-------------
conda-gcc7 + .cc           | undefined                   | undefined      | undefined
conda-gcc9 + .cc           | defined                     | undefined      | undefined
recent glibc + gcc10 + .c  | undefined                   | undefined      | defined
recent glibc + gcc10 + .cc | defined                     | defined        | …
=> Fix aligned_alloc

src/os.c
mi_align_down_ptr was implemented with multiplication and division,
which can be converted to equivalent and deterministic bit operations.
=> Rewrite align_down with bitwise operations

CMakeLists.txt
The standard way of cmake install to a destination folder is the following pattern:
```shell
cd <BUILD_DIR>
cmake <SRC_DIR>
cmake --build <BUILD_DIR>
cmake --install <BUILD_DIR> --prefix <INSTALL_DIR>
```
Right now, the `<INSTALL_DIR>` folder passed in cmake --install command is ignored,
and always installed into `C:/Program Files(x86)/...`, which is the default
`CMAKE_INSTALL_PREFIX` value passed at the `cmake <SRC_DIR>` call.
Thus, it is not possible to install the binaries into different folders
without rerun the cmake/build process.
The important thing here is, the cmake variable `CMAKE_INSTALL_PREFIX`
is supposed to be passed at `cmake --install` time with the `--prefix` argument.
In cmake file, `install` with relative path will use that prefix automaticlly.
And it is the best …
=> [CMake] Respect CMAKE_INSTALL_PREFIX at install time

CMakeLists.txt
This fixes the use of mimalloc on 32-bit Windows when building with CMake.
Without it, one would get link errors like:
```
init.obj error LNK2019: unresolved external symbol __imp__mi_allocator_init referenced in function "void __cdecl mi_process_load(void)" (?mi_process_load@@YAXXZ)
10:58:29
init.obj error LNK2019: unresolved external symbol __imp__mi_allocator_done referenced in function "void __cdecl mi_process_done(void)" (?mi_process_done@@YAXXZ)
10:58:29
..\..\..\..\thirdparty\mimalloc\bin\mimalloc-redirect.lib warning LNK4272: library machine type 'x64' conflicts with target machine type 'x86'
```
because it would try to link `bin\mimalloc-redirect.lib` (64-bit) to a 32-bit mimalloc.dll.
Also, without this patch, `bin\mimalloc-redirect32.{lib,dll}` are unused in CMake, they are …
=> [Windows] Correctly choose 32-bit version of mimalloc-redirect{,32}.dll in CMake.

src/os.c
In _mi_os_good_alloc_size, overflow caused by alignment size is rare,
and this patch added the appropriate branch hint during range checks.
=> Add branch hint for _mi_os_good_alloc_size

include/mimalloc-internal.h, include/mimalloc.h
When building some code against mimalloc with C inside Visual Studio
with ClangCL, the compiler complains about `__GNUC__` being undefined.
Reported by Mojca Miklavec.
Close #422
=> Eliminate preprocessor warnings due to undefined "__GNUC__" with ClangCL

src/alloc.c, src/random.c
Define ``_DEFAULT_SOURCE`` in ``random.c`` and ``alloc.c``. The macro
is required for ``syscall()`` and ``realpath()``. Other files like
``os.c`` already define the macro.
Signed-off-by: Christian Heimes <christian@python.org>
=> Define _DEFAULT_SOURCE for syscall and realpath

include/mimalloc-types.h, src/arena.c, src/os.c, src/segment.c, src/stats.c
SI preﬁxes [the decimal prefixes] refer strictly to powers of 10. They
should not be used to indicate powers of 2. e.g., one kilobit
represents 1000 bits instead of 1024 bits. IEC 60027‐2 symbols are
formed adding a "i" to the SI symbol (e.g. G + i = Gi).
=> Distinguish SI and Binary Prefixes

include/mimalloc-internal.h, src/init.c, src/random.c
The ``_os_random_weak`` function is the only non-static function
besides ``_ZSt15get_new_handlerv`` that is not prefixed with ``mi`` or
``_mi``.
The discrepancy was discovered by CPython's smelly script. The checker
looks for exported symbols that don't have well-defined prefixes.
Signed-off-by: Christian Heimes <christian@python.org>
=> Rename _os_random_weak to _mi_os_random_weak

readme.md
The .so files are usually in `/usr/lib`, not `/usr/bin`. The updated path is the same as below in the text.
=> Fix preload path in documentation example

CMakeLists.txt
Rebase of https://github.com/microsoft/mimalloc/pull/463 on `dev` branch.
=> cmake: removed hardcoded names for top level configuration

doc/mimalloc-doc.h, include/mimalloc.h, readme.md, src/init.c, src/options.c
Currently, huge page reservation reserves huge pages evenly among the given number of numa nodes. Consider adding an option to reserve huge pages at a specific NUMA node.
=> add option to reserve huge os pages at a specific numa node.

CMakeLists.txt, cmake/mimalloc-config-version.cmake
This is the pull request for the issue490: mimalloc: set SOVERSION for mimalloc shared lib (required for proper unix builds) #490 
The reason is following:
SOVERSION is required for proper unix builds.
comments on the proposed patches:
A) in CMakeLists.txt 
1)  add SOVERSION ${mi_version_major}
2) remove the hack with symlinks:
-if(NOT WIN32 AND MI_BUILD_SHARED AND NOT MI_INSTALL_TOPLEVEL)
...
endif()
first, it does thing wrong on unix, and, second, when we set SOVERSION, cmake will do it for us, and will do it properly.
B)
it is optional, but it would be nice to show .so.version as real version 2.0.3, not 2.0
for this, in cmake/mimalloc-config-version.cmake
-set(mi_version ${mi_version_major}.${mi_version_minor})
+set(mi_version_patch 3)
+set(mi_version …
=> Pull request for issue #490:  set SOVERSION for mimalloc shared lib

azure-pipelines.yml, src/random.c
The implementation of `arc4random_buf` differs from its documentation. It is documented as
> "always successful, and no return value is reserved to indicate an error"
for the sake of FreeBSD compatibility [1]. However, the actual implementation on macOS invokes function "ccrng_generate" [2] without validating the error cases. It might fail silently[3], which leads to unexpected source of entropy.
The original `arc4random` used the RC4 a.k.a. ARC4 algorithm, and ChaCha20 based implementation was introduced in FreeBSD 12.0. Since macOS 10.12, it was replaced with the NIST-approved AES cipher, and it may be replaced again in the future as cryptographic techniques advance. Therefore, we should not assume that arc4random never fails.
On the contrary, CCRandomGenerateBytes(), part of …
=> Use secure random generator on macOS

src/options.c
1. Avoid the infinite recursion mentioned in #502 
2. Add a special case for an invalid "verbose" option value
=> "verbose" option fixes

src/options.c
They used strncpy() and strncat(), which behave almost, but not
quite like the ...l... functions.
Since these functions are not standard, and not all OSes have
comparable functions available, just add a implementations.
Addresses first issue raised in microsoft/mimalloc#502.
=> Replace mi_strlcpy() and mi_strlcat() with versions written from scratch

include/mimalloc-types.h
CPython and Windows CRT debug builds use different values for uninit,
freed, and padding bytes. Make ``MI_DEBUG_*`` constants conditional to
allow embedders to override the constants.
Windows dbgheap:
```
_bNoMansLandFill = 0xFD
_bDeadLandFill   = 0xDD
_bCleanLandFill  = 0xCD
```
Python memory debug
```
PYMEM_CLEANBYTE      0xCD
PYMEM_DEADBYTE       0xDD
PYMEM_FORBIDDENBYTE  0xFD
```
Signed-off-by: Christian Heimes <christian@python.org>
=> Allow overrides of MI_DEBUG memory constants

src/os.c
Emscripten/WASI builds referenced `KK_UNUSED` macro. Changed this to `MI_UNUSED`.
=> Fix build error caused by undefined macro in Emscripten/WASI build

CMakeLists.txt
Otherwise a static only build would not be usable as cmake package
(as mimalloc.cmake wouldn't be generated).
=> cmake: export mimalloc-static as well

CMakeLists.txt
From README:
> the mimalloc-redirect.dll (or mimalloc-redirect32.dll) must be put in the same folder as the main mimalloc-override.dll at runtime
So it should be installed wherever mimalloc dll goes...
=> Include mimalloc-redirect.dll with cmake install

include/mimalloc-new-delete.h
So far, mimalloc does not override the `nothrow` variants of the `delete` operator because it assumes that their implementation in the C++ standard library redirects to the default `delete` operators. This is not the case for GNU libstdc++ < 9, where `std::free()` is called directly.
This issue might be the cause for the crashes reported in #261.
Upstream bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68210
This commit ensures that the `nothrow` `delete` operators are properly overridden by mimalloc.
=> Fix compatibility with GNU libstdc++ < 9

src/os.c
Fix warning: function declaration isn't a prototype [-Wstrict-prototypes]
In C int foo() and int foo(void) are different functions.
=> Fix strict function prototype warnings

CMakeLists.txt, cmake/JoinPaths.cmake, mimalloc.pc.in
pkg-config allows using the library in build systems that are not cmake, by exporting the same information from the cmake -config files in a buildsystem-neutral format.
Fixes #16
...
Submission containing materials of a third party:
Author: Jan Tojnar (@jtojnar)
Source: https://github.com/jtojnar/cmake-snips
License: dual-licensed under [MIT](https://github.com/jtojnar/cmake-snips/blob/master/LICENSE.md) and [CC0 1.0](https://creativecommons.org/publicdomain/zero/1.0/).
=> cmake: add pkg-config file

include/mimalloc/atomic.h
=> Fix ATOMIC_VAR_INIT deprecation warnings for C17

include/mimalloc.h, test/test-api.c
Before it would not work to create the `mi_heap_stl_allocator` types with passing in a `mi_heap_t*`, since `sizeof` is used and it gives a compilation error. This change fixes that.
Steps to reproduce the current error:
```cpp
include <mimalloc.h>
#include <vector>
int main() {
mi_heap_t *hp = mi_heap_new();
mi_heap_destroy_stl_allocator<int> thisOne(hp);
mi_heap_destroy(hp);
}
```
Compilation error is:
```
====================[ Build | mimalloc-stuff | Debug ]==========================
/home/rhermes/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/bin/cmake --build /home/rhermes/commons/projects/measure-everything/cmake-build-debug --target mimalloc-stuff -j 22
[1/2] Building CXX object CMakeFiles/mimalloc-stuff.dir/mimalloc-stuff/main.cpp.o
FAILED: …
```
=> Avoid compilation error when passing in heap_t to C++ allocators

src/alloc-override.c
=> Only interpose strndup if it exists

src/prim/osx/alloc-override-zone.c
This field exists in the 10.7 and later SDKs.
=> Fix min macOS for pressure_relief

src/prim/emscripten/prim.c
https://github.com/emscripten-core/emscripten/pull/20704 removed the maximum alignment limit from emmalloc, so we no longer need it in the mimalloc port. Without it, we can properly use the 4GB-aligned pages that mimalloc requests.
(Emscripten-side testing in https://github.com/emscripten-core/emscripten/pull/21905)
=> Emscripten: Remove no-longer-needed minimum emmalloc alignment

src/prim/osx/alloc-override-zone.c
`__attribute__((constructor))` does not mark the symbol as used, so the linker ends up dead-stripping the symbol when linked statically.
Adding the `used` attribute fixes that.
=> macOS: Fix linking statically

src/arena-abandon.c
Fix the following android errors.
error: no matching function for call to 'atomic_store_explicit'
mi_atomic_store_release(&segment->thread_id, 0);
=> Fix build error on x64-android

src/libc.c
`va_arg` with type `long` was used for both `int` and `long` arguments, but x86_64 Linux has 64-bit `long`, so passing an `int` argument to `_mi_vsnprintf` results in undefined behaviour. For example, here: https://github.com/microsoft/mimalloc/blob/db3d8485d2f45a6f179d784f602f9eff4f60795c/src/prim/unix/prim.c#L521-L524
`intptr_t` was used as the largest integer type, but on 32-bit systems it is 32-bit wide, while `long long` is 64-bit. `intmax_t` can be used instead.
=> Fix int and long handling and the use of (u)intptr_t in _mi_vsnprintf

include/mimalloc/internal.h, src/init.c
FSRM is better used for buffer <= 128 bytes and EMRS, if supported for larger chunks.
=> _mi_memcpy/_mi_memzero: tighten criteria for intrinsics for windows.

include/mimalloc/internal.h, src/init.c, src/segment-map.c
The segment map was never being freed, even when `destroy_on_exit` is true. We have a use case where we need all OS memory allocated by a shared library to be freed when the library is unloaded, and we noticed that the segment map parts were never freed.
=> Free segment map when destroy_on_exit is set

src/prim/unix/prim.c
This change fixes the "implicit declaration of function 'getenv'" warning. Since stdlib.h is completely portable, as it is defined by the C standard, we can safely include it unconditionally.
=> Add a missing #include

src/prim/unix/prim.c
Tag 100 is assigned to "IOAccelerator" (the GPU driver stack on Apple silicon), which makes for confusing output when debugging.
To avoid conflicts, use a tag in the reserved application-specific range from 240–255 (inclusive).
All assigned tags: https://github.com/apple-oss-distributions/xnu/blob/94d3b452840153a99b38a3a9659680b2a006908e/osfmk/mach/vm_statistics.h#L773-L775
=> Change macOS mmap tag to fix conflict with IOAccelerator

include/mimalloc/prim.h
```
$ uname -srvmpio
CYGWIN_NT-10.0-22000 3.5.3-1.x86_64 2024-04-03 17:25 UTC x86_64 unknown unknown Cygwin
$ cd /tmp
$ git clone https://github.com/microsoft/mimalloc.git
$ cd mimalloc
$ cmake -DMI_BUILD_STATIC:BOOL=OFF -DMI_BUILD_OBJECT:BOOL=OFF -DMI_INSTALL_TOPLEVEL:BOOL=ON .
$ make VERBOSE=1
:
[  4%] Linking C shared library cygmimalloc-1.dll
/usr/bin/cmake.exe -E cmake_link_script CMakeFiles/mimalloc.dir/link.txt --verbose=1
/usr/bin/cc -O3 -DNDEBUG -shared -Wl,--enable-auto-import -o cygmimalloc-1.dll -Wl,--out-implib,libmimalloc.dll.a -Wl,--major-image-version,1,--minor-image-version,8 CMakeFiles/mimalloc.dir/src/alloc.c.o "CMakeFiles/mimalloc.dir/src/alloc-aligned.c.o" "CMakeFiles/mimalloc.dir/src/alloc-posix.c.o" CMakeFiles/mimalloc.dir/src/arena.c.o …
```
=> Build on cygwin

CMakeLists.txt
When using `-DCMAKE_OSX_ARCHITECTURES='x86_64;arm64'` to build universal binaries, the existing `-march=armv8.1-a` ends up applying to both targets but is obviously invalid for the x86_64 target. Prefix with `-Xarch_arm64` to ensure it only applies to the arm64 target.
=> support MI_OPT_ARCH when targeting multiple CMAKE_OSX_ARCHITECTURES

CMakeLists.txt
CMake handles import lib for it automatically, and using `.dll.lib` extension is MSVC-specific hack
fixes #1044
=> cmake: don't change properties of import lib on Windows/MinGW

include/mimalloc/atomic.h
Previously, `mi_atomic_yield` would not be defined on ARM32 big-endian architectures if they were pre-ARMv7.
Rework the #ifdef guard to be more readable and collapse the ARM guards so both little and big endian are handled via the same mechanism.
Now, ARMv7+ will utilize `yield` while older targets will use `nop` regardless of endianness.
closes #1046
=> atomic: fix mi_atomic_yield for big-endian arm32

src/options.c
I'm hitting infinite recursion here when trying to run statically linked mimalloc from `dev3` with `MI_DEBUG_FULL=ON`+ `MI_CHECK_FULL=ON` on Android.
Attaching top of the callstack:
```
_mi_heap_main_get (mimalloc/src/init.c:272)
mi_prim_get_default_heap (mimalloc/include/mimalloc/prim.h:411)
mi_malloc (mimalloc/src/alloc.c:208)
__emutls_get_address (@__emutls_get_address:65)
mi_recurse_enter_prim (mimalloc/src/options.c:421)
mi_recurse_enter (mimalloc/src/options.c:434)
mi_vfprintf (mimalloc/src/options.c:463)
_mi_fprintf (mimalloc/src/options.c:472)
_mi_assert_fail (mimalloc/src/options.c:539)
_mi_page_map_register (mimalloc/src/page-map.c:284)
mi_arenas_page_alloc_fresh (mimalloc/src/arena.c:703)
mi_arenas_page_regular_alloc (mimalloc/src/arena.c:727)
_mi_arenas_page_alloc …
```
=> fix recursion in TLS init on Android
